# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AkunPerkiraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode_akun', models.CharField(max_length=50)),
                ('saldo_normal', models.CharField(choices=[('D', 'Debet'), ('K', 'Kredit')], max_length=10)),
                ('kategori', models.CharField(choices=[('1', 'Aktiva'), ('2', 'Hutang'), ('3', 'Modal'), ('4', 'Pendapatan'), ('5', 'HPP'), ('6', 'Biaya')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_identitas', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=250)),
                ('jk', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(max_length=100, verbose_name='tempat lahir')),
                ('tgl_lahir', models.DateField(verbose_name='tanggal lahir')),
                ('alamat', models.CharField(max_length=300)),
                ('pekerjaan', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('pic', models.FileField(upload_to='', verbose_name='foto')),
                ('scan_identitas', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Koperasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='nama koperasi')),
                ('badan_hukum', models.CharField(max_length=200, verbose_name='nomor badan hukum')),
                ('telp', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=250)),
                ('fax', models.CharField(max_length=50)),
                ('tgl', models.DateTimeField(verbose_name='tanggal daftar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koperasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koperasi.Koperasi')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_daftar', models.DateField()),
                ('tgl_berakhir', models.DateField()),
                ('masa_aktif', models.IntegerField()),
                ('status', models.BooleanField()),
                ('koperasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koperasi.Koperasi')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateTimeField(verbose_name='tanggal')),
                ('dari_akun', models.CharField(max_length=100)),
                ('untuk_akun', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('koperasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koperasi.Koperasi')),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiPinjam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateTimeField(verbose_name='tanggal')),
                ('jumlah', models.IntegerField()),
                ('keterangan', models.CharField(max_length=200)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koperasi.Anggota')),
                ('koperasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koperasi.Koperasi')),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiSimpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateTimeField(verbose_name='tanggal')),
                ('jumlah', models.IntegerField()),
                ('keterangan', models.CharField(max_length=200)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koperasi.Anggota')),
                ('koperasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koperasi.Koperasi')),
            ],
        ),
        migrations.AddField(
            model_name='anggota',
            name='koperasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koperasi.Koperasi'),
        ),
        migrations.AddField(
            model_name='akunperkiraan',
            name='koperasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koperasi.Koperasi'),
        ),
    ]
